In [1]:
library(popbio)

### Question 2

In [2]:
leslie =  matrix(c(
    0, 3.5, 1.5, 0.5, 
    0.4, 0, 0, 0,
    0, 0.5, 0, 0,
    0, 0, 0.3, 0), nr = 4, byrow=TRUE)

In [3]:
leslie

[,1] [,2] [,3] [,4]
[1,] 0.0  3.5  1.5  0.5 
[2,] 0.4  0.0  0.0  0.0 
[3,] 0.0  0.5  0.0  0.0 
[4,] 0.0  0.0  0.3  0.0

### Question 3

In [4]:
N0 = matrix(c(250,100,30,15), ncol=1)
years = 5
N.projections = matrix(0, nrow = nrow(leslie), ncol = years + 1)
N.projections[, 1] <- N0

for(i in 1: years) {
    N.projections[, i + 1] = leslie %*% N.projections[, i]
}

N.projections

[,1] [,2]  [,3]  [,4]  [,5]   [,6]    
[1,] 250  402.5 429.5 646.0 729.55 1045.325
[2,] 100  100.0 161.0 171.8 258.40  291.820
[3,]  30   50.0  50.0  80.5  85.90  129.200
[4,]  15    9.0  15.0  15.0  24.15   25.770

In [5]:
pop.projection(A = leslie, n = N0, iterations = years+1)

$lambda
[1] 1.358939

$stable.stage
[1] 0.70056598 0.19557474 0.08658850 0.01727079

$stage.vectors
       0     1     2     3      4        5
[1,] 250 402.5 429.5 646.0 729.55 1045.325
[2,] 100 100.0 161.0 171.8 258.40  291.820
[3,]  30  50.0  50.0  80.5  85.90  129.200
[4,]  15   9.0  15.0  15.0  24.15   25.770

$pop.sizes
[1]  395.000  561.500  655.500  913.300 1098.000 1492.115

$pop.changes
[1] 1.421519 1.167409 1.393288 1.202234 1.358939

### Question 4

In [6]:
analysis = eigen.analysis(leslie)

What is the growth rate, and what does this tell us about the growth of the population?

In [7]:
growth_rate = round(analysis$lambda1, 2)
print(paste("Growth rate", growth_rate, "population is increasing"))

[1] "Growth rate 1.29 population is increasing"


What is the stable age distribution, and can you confirm this using the projected population sizes in the last time step?

In [8]:
stable_age_distribution = N.projections[, 6]
stable_age_distribution = stable_age_distribution/sum(stable_age_distribution)
stable_age_distribution

[1] 0.70056598 0.19557474 0.08658850 0.01727079

Which age group contributes most to population growth in absolute and relative terms?

In [9]:
analysis

$lambda1
[1] 1.285146

$stable.stage
[1] 0.68464490 0.21309479 0.08290683 0.01935348

$sensitivities
          [,1]      [,2]       [,3]        [,4]
[1,] 0.4622492 0.1438744 0.05597590 0.013066817
[2,] 1.4851444 0.4622492 0.17984303 0.041981925
[3,] 0.5815110 0.1809945 0.07041787 0.016438100
[4,] 0.1798430 0.0559759 0.02177803 0.005083786

$elasticities
          [,1]       [,2]        [,3]        [,4]
[1,] 0.0000000 0.39183130 0.065334086 0.005083786
[2,] 0.4622492 0.00000000 0.000000000 0.000000000
[3,] 0.0000000 0.07041787 0.000000000 0.000000000
[4,] 0.0000000 0.00000000 0.005083786 0.000000000

$repro.value
[1] 1.0000000 3.2128654 1.2580034 0.3890608

$damping.ratio
[1] 1.200536

First age group N1 has the highest elasticity and sensitivity. 