In [1]:
library(popbio)

### Question 2

In [2]:
leslie =  matrix(c(
    0, 3.5, 1.5, 0.5, 
    0.4, 0, 0, 0,
    0, 0.5, 0, 0,
    0, 0, 0.3, 0), nr = 4, byrow=TRUE)

In [3]:
leslie

[,1] [,2] [,3] [,4]
[1,] 0.0  3.5  1.5  0.5 
[2,] 0.4  0.0  0.0  0.0 
[3,] 0.0  0.5  0.0  0.0 
[4,] 0.0  0.0  0.3  0.0

### Question 3

In [4]:
N0 = matrix(c(250,100,30,15), ncol=1)
years = 5
N.projections = matrix(0, nrow = nrow(leslie), ncol = years + 1)
N.projections[, 1] <- N0

for(i in 1: years) {
    N.projections[, i + 1] = leslie %*% N.projections[, i]
}

N.projections

[,1] [,2]  [,3]  [,4]  [,5]   [,6]    
[1,] 250  402.5 429.5 646.0 729.55 1045.325
[2,] 100  100.0 161.0 171.8 258.40  291.820
[3,]  30   50.0  50.0  80.5  85.90  129.200
[4,]  15    9.0  15.0  15.0  24.15   25.770

In [5]:
pop.projection(A = leslie, n = N0, iterations = years+1)

$lambda
[1] 1.358939

$stable.stage
[1] 0.70056598 0.19557474 0.08658850 0.01727079

$stage.vectors
       0     1     2     3      4        5
[1,] 250 402.5 429.5 646.0 729.55 1045.325
[2,] 100 100.0 161.0 171.8 258.40  291.820
[3,]  30  50.0  50.0  80.5  85.90  129.200
[4,]  15   9.0  15.0  15.0  24.15   25.770

$pop.sizes
[1]  395.000  561.500  655.500  913.300 1098.000 1492.115

$pop.changes
[1] 1.421519 1.167409 1.393288 1.202234 1.358939

### Question 4

In [6]:
analysis = eigen.analysis(leslie)

What is the growth rate, and what does this tell us about the growth of the population?

In [7]:
growth_rate = round(analysis$lambda1, 2)
print(paste("Growth rate", growth_rate, "population is increasing"))

[1] "Growth rate 1.29 population is increasing"


What is the stable age distribution, and can you confirm this using the projected population sizes in the last time step?

In [8]:
stable_age_distribution = N.projections[, 6]
stable_age_distribution = stable_age_distribution/sum(stable_age_distribution)
stable_age_distribution

[1] 0.70056598 0.19557474 0.08658850 0.01727079

Which age group contributes most to population growth in absolute and relative terms?

In [9]:
analysis

$lambda1
[1] 1.285146

$stable.stage
[1] 0.68464490 0.21309479 0.08290683 0.01935348

$sensitivities
          [,1]      [,2]       [,3]        [,4]
[1,] 0.4622492 0.1438744 0.05597590 0.013066817
[2,] 1.4851444 0.4622492 0.17984303 0.041981925
[3,] 0.5815110 0.1809945 0.07041787 0.016438100
[4,] 0.1798430 0.0559759 0.02177803 0.005083786

$elasticities
          [,1]       [,2]        [,3]        [,4]
[1,] 0.0000000 0.39183130 0.065334086 0.005083786
[2,] 0.4622492 0.00000000 0.000000000 0.000000000
[3,] 0.0000000 0.07041787 0.000000000 0.000000000
[4,] 0.0000000 0.00000000 0.005083786 0.000000000

$repro.value
[1] 1.0000000 3.2128654 1.2580034 0.3890608

$damping.ratio
[1] 1.200536

First age group N1 has the highest elasticity and sensitivity. 

## Exercise 2

In [10]:
N0 = c(800,200,30,60,40,15)
leftkovich =  matrix(c(
    0.83, 0, 0, 0.2, 1.56, 2.63,
    0.06, 0.73, 0, 0, 0, 0,
    0, 0.01, 0.93, 0, 0, 0,
    0, 0, 0.07, 0.95, 0, 0,
    0, 0, 0, 0.05, 0.94, 0,
    0, 0, 0, 0, 0.04, 0.83), nr = 6, byrow=TRUE)

In [11]:
projection = pop.projection(A = leftkovich, n = N0, iterations = years+1)

In [12]:
analysis = eigen.analysis(leftkovich)

In [13]:
analysis$lambda1

[1] 0.990235

What is the growth rate, and what does this tell us about the growth of the population?

Population is likely to stay unchanged over time.

What is the stable stage distribution, and can you confirm this using the projected population sizes in the last time step?

In [14]:
projection$stable.stage

[1] 0.69438675 0.16963476 0.02842422 0.05465145 0.04136407 0.01153876

In [15]:
last = projection$stage.vectors[, 5]
last/sum(last)

[1] 0.69472496 0.17081908 0.02814075 0.05435102 0.04026938 0.01169481

In [17]:
analysis

$lambda1
[1] 0.990235

$stable.stage
[1] 0.70508967 0.16256609 0.02698866 0.04695433 0.04673471 0.01166654

$sensitivities
           [,1]       [,2]        [,3]        [,4]        [,5]        [,6]
[1,] 0.08730164 0.02012834 0.003341637 0.005813714 0.005786522 0.001444509
[2,] 0.23314626 0.05375440 0.008924119 0.015526006 0.015453385 0.003857681
[3,] 6.06728085 1.39887754 0.232236788 0.404040964 0.402151114 0.100390350
[4,] 5.22089237 1.20373348 0.199839648 0.347677063 0.346050848 0.086385850
[5,] 3.85204216 0.88813018 0.147444287 0.256520650 0.255320807 0.063736602
[6,] 1.43291639 0.33037445 0.054847618 0.095422799 0.094976471 0.023709299

$elasticities
           [,1]       [,2]       [,3]        [,4]        [,5]        [,6]
[1,] 0.07317492 0.00000000 0.00000000 0.001174209 0.009115992 0.003836523
[2,] 0.01412672 0.03962768 0.00000000 0.000000000 0.000000000 0.000000000
[3,] 0.00000000 0.01412672 0.21811006 0.000000000 0.000000000 0.000000000
[4,] 0.00000000 0.00000000 0.01412672 0.333550340 0.000000000 0.000000000
[5,] 0.00000000 0.00000000 0.00000000 0.012952514 0.242368293 0.000000000
[6,] 0.00000000 0.00000000 0.00000000 0.000000000 0.003836523 0.019872777

$repro.value
[1]  1.000000  2.670583 69.497903 59.802913 44.123366 16.413396

$damping.ratio
[1] 1.065967